# Generated by Django 4.2.8 on 2025-11-28 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage_os', models.BooleanField(default=False, verbose_name='Gerenciar OS')),
                ('can_manage_vendas', models.BooleanField(default=False, verbose_name='Gerenciar Vendas')),
                ('can_manage_compras', models.BooleanField(default=False, verbose_name='Gerenciar Compras')),
                ('can_manage_financeiro', models.BooleanField(default=False, verbose_name='Gerenciar Financeiro')),
                ('can_view_relatorios', models.BooleanField(default=False, verbose_name='Ver Relatórios')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.group')),
            ],
        ),
    ]
