# Generated by Django 4.2.26 on 2025-11-23 02:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número')),
                ('tipo', models.CharField(choices=[('orcamento', 'Orçamento'), ('venda', 'Venda')], default='venda', max_length=10, verbose_name='Tipo')),
                ('data_venda', models.DateTimeField(auto_now_add=True, verbose_name='Data da Venda')),
                ('data_entrega', models.DateField(blank=True, null=True, verbose_name='Data de Entrega')),
                ('status', models.CharField(choices=[('orcamento', 'Orçamento'), ('aprovado', 'Aprovado'), ('faturado', 'Faturado'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='orcamento', max_length=20, verbose_name='Status')),
                ('valor_produtos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor dos Produtos')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do Desconto')),
                ('valor_acrescimo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do Acréscimo')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='erp.cliente', verbose_name='Cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-data_venda'],
            },
        ),
        migrations.CreateModel(
            name='PDV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('numero_caixa', models.IntegerField(default=1, verbose_name='Número do Caixa')),
                ('data_abertura', models.DateTimeField(auto_now_add=True, verbose_name='Data de Abertura')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fechamento')),
                ('valor_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Inicial')),
                ('valor_vendas', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor de Vendas')),
                ('valor_sangrias', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor de Sangrias')),
                ('valor_suprimentos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor de Suprimentos')),
                ('valor_final', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Final')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado')], default='aberto', max_length=20, verbose_name='Status')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caixas', to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'PDV',
                'verbose_name_plural': 'PDVs',
                'ordering': ['-data_abertura'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoPDV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('venda', 'Venda'), ('sangria', 'Sangria'), ('suprimento', 'Suprimento')], max_length=20, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('pdv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='vendas.pdv', verbose_name='PDV')),
            ],
            options={
                'verbose_name': 'Movimento do PDV',
                'verbose_name_plural': 'Movimentos do PDV',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço Unitário')),
                ('preco_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço Total')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto')),
                ('acrescimo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Acréscimo')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_venda', to='erp.produto', verbose_name='Produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.venda', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Item da Venda',
                'verbose_name_plural': 'Itens da Venda',
                'ordering': ['produto__nome'],
            },
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('debito', 'Débito'), ('credito', 'Crédito'), ('pix', 'PIX'), ('boleto', 'Boleto'), ('cheque', 'Cheque')], max_length=20, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor')),
                ('parcelas', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Parcelas')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='vendas.venda', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Forma de Pagamento',
                'verbose_name_plural': 'Formas de Pagamento',
            },
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['numero'], name='vendas_vend_numero_03706f_idx'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['cliente', '-data_venda'], name='vendas_vend_cliente_a44f81_idx'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['status'], name='vendas_vend_status_be1af5_idx'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['-data_venda'], name='vendas_vend_data_ve_bf430b_idx'),
        ),
    ]
