# Generated by Django 4.2.8 on 2025-11-25 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_contapagar_categoria_dre_contareceber_categoria_dre'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentopdv',
            name='categoria_dre',
            field=models.ForeignKey(blank=True, help_text='Categoria para o relatório DRE', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_pdv', to='financeiro.categoriadre', verbose_name='Categoria DRE'),
        ),
    ]
