# Generated by Django 4.2.8 on 2025-11-26 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_servico'),
        ('vendas', '0002_movimentopdv_categoria_dre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemvenda',
            options={'ordering': ['produto__nome', 'servico__nome'], 'verbose_name': 'Item da Venda', 'verbose_name_plural': 'Itens da Venda'},
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_venda', to='erp.servico', verbose_name='Serviço'),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_venda', to='erp.produto', verbose_name='Produto'),
        ),
    ]
