# Generated by Django 4.2.8 on 2025-11-26 22:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_formarecebimento_alter_pagamento_forma_pagamento_and_more'),
        ('vendas', '0003_alter_itemvenda_options_itemvenda_servico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecebimentoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_bruto', models.DecimalField(decimal_places=2, help_text='Valor antes das taxas', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Bruto')),
                ('taxa_percentual', models.DecimalField(decimal_places=2, default=0, help_text='Taxa aplicada pela operadora', max_digits=5, verbose_name='Taxa Percentual (%)')),
                ('taxa_fixa', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa Fixa (R$)')),
                ('valor_taxa_total', models.DecimalField(decimal_places=2, default=0, help_text='Soma de todas as taxas', max_digits=10, verbose_name='Valor Total de Taxas')),
                ('valor_liquido', models.DecimalField(decimal_places=2, default=0, help_text='Valor que realmente entra no caixa', max_digits=10, verbose_name='Valor Líquido')),
                ('parcelas', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Parcelas')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('data_recebimento', models.DateField(blank=True, null=True, verbose_name='Data de Recebimento')),
                ('data_prevista_recebimento', models.DateField(blank=True, help_text='Calculada com base nos dias de recebimento da forma', null=True, verbose_name='Data Prevista de Recebimento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('recebido', 'Recebido'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('forma_recebimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos_venda', to='financeiro.formarecebimento', verbose_name='Forma de Recebimento')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recebimentos', to='vendas.venda', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Recebimento da Venda',
                'verbose_name_plural': 'Recebimentos das Vendas',
                'ordering': ['-data_vencimento'],
            },
        ),
        migrations.DeleteModel(
            name='FormaPagamento',
        ),
    ]
