# Generated by Django 4.2.8 on 2025-11-26 19:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('codigo_interno', models.CharField(max_length=50, unique=True, verbose_name='Código Interno')),
                ('preco_custo', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Custo Estimado')),
                ('preco_venda', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço de Venda')),
                ('margem_lucro', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Margem de Lucro (%)')),
                ('tempo_estimado', models.IntegerField(default=0, help_text='Tempo médio em minutos', verbose_name='Tempo Estimado (min)')),
                ('categoria', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'servico'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicos', to='erp.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['codigo_interno'], name='erp_servico_codigo__23715e_idx'), models.Index(fields=['nome'], name='erp_servico_nome_eae166_idx'), models.Index(fields=['active'], name='erp_servico_active_94923d_idx')],
            },
        ),
    ]
