# Generated by Django 4.2.26 on 2025-11-23 02:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria Financeira',
                'verbose_name_plural': 'Categorias Financeiras',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('banco', models.CharField(max_length=100, verbose_name='Banco')),
                ('agencia', models.CharField(max_length=20, verbose_name='Agência')),
                ('conta', models.CharField(max_length=20, verbose_name='Conta')),
                ('tipo_conta', models.CharField(default='Conta Corrente', max_length=50, verbose_name='Tipo de Conta')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Inicial')),
                ('saldo_atual', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Atual')),
            ],
            options={
                'verbose_name': 'Conta Bancária',
                'verbose_name_plural': 'Contas Bancárias',
                'ordering': ['banco', 'agencia'],
            },
        ),
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Original')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Pago')),
                ('juros', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Juros')),
                ('multa', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Multa')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('forma_pagamento', models.CharField(blank=True, max_length=50, verbose_name='Forma de Pagamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado'), ('atrasado', 'Atrasado')], default='pendente', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('numero_documento', models.CharField(blank=True, max_length=50, verbose_name='Número do Documento')),
                ('categoria', models.ForeignKey(limit_choices_to={'tipo': 'despesa'}, on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='financeiro.categoriafinanceira', verbose_name='Categoria')),
                ('conta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='financeiro.contabancaria', verbose_name='Conta Bancária')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='erp.fornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
                'ordering': ['-data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Original')),
                ('valor_recebido', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Recebido')),
                ('juros', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Juros')),
                ('multa', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Multa')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_recebimento', models.DateField(blank=True, null=True, verbose_name='Data de Recebimento')),
                ('forma_recebimento', models.CharField(blank=True, max_length=50, verbose_name='Forma de Recebimento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('recebido', 'Recebido'), ('cancelado', 'Cancelado'), ('atrasado', 'Atrasado')], default='pendente', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('numero_documento', models.CharField(blank=True, max_length=50, verbose_name='Número do Documento')),
                ('categoria', models.ForeignKey(limit_choices_to={'tipo': 'receita'}, on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber', to='financeiro.categoriafinanceira', verbose_name='Categoria')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber', to='erp.cliente', verbose_name='Cliente')),
                ('conta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber', to='financeiro.contabancaria', verbose_name='Conta Bancária')),
            ],
            options={
                'verbose_name': 'Conta a Receber',
                'verbose_name_plural': 'Contas a Receber',
                'ordering': ['-data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='FluxoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10, verbose_name='Tipo')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fluxo_caixa', to='financeiro.categoriafinanceira', verbose_name='Categoria')),
                ('conta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fluxo_caixa', to='financeiro.contabancaria', verbose_name='Conta Bancária')),
                ('conta_pagar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fluxo_caixa', to='financeiro.contapagar', verbose_name='Conta a Pagar')),
                ('conta_receber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fluxo_caixa', to='financeiro.contareceber', verbose_name='Conta a Receber')),
            ],
            options={
                'verbose_name': 'Fluxo de Caixa',
                'verbose_name_plural': 'Fluxo de Caixa',
                'ordering': ['-data'],
            },
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['numero'], name='financeiro__numero_a77fb4_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['cliente', '-data_vencimento'], name='financeiro__cliente_838023_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['status'], name='financeiro__status_36b422_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['-data_vencimento'], name='financeiro__data_ve_acefe2_idx'),
        ),
        migrations.AddIndex(
            model_name='contapagar',
            index=models.Index(fields=['numero'], name='financeiro__numero_20246c_idx'),
        ),
        migrations.AddIndex(
            model_name='contapagar',
            index=models.Index(fields=['fornecedor', '-data_vencimento'], name='financeiro__fornece_7be395_idx'),
        ),
        migrations.AddIndex(
            model_name='contapagar',
            index=models.Index(fields=['status'], name='financeiro__status_9cb6c1_idx'),
        ),
        migrations.AddIndex(
            model_name='contapagar',
            index=models.Index(fields=['-data_vencimento'], name='financeiro__data_ve_50eeaf_idx'),
        ),
    ]
