# Generated by Django 4.2.8 on 2025-11-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDRE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('deducao', 'Dedução'), ('custo', 'Custo'), ('despesa', 'Despesa')], max_length=20)),
                ('codigo', models.CharField(help_text='Código da categoria (ex: 1, 3, 5...)', max_length=10, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição no DRE')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria DRE',
                'verbose_name_plural': 'Categorias DRE',
                'db_table': 'categoria_dre',
                'ordering': ['ordem', 'codigo'],
            },
        ),
    ]
