# Generated by Django 4.2.8 on 2025-11-25 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_categoriadre'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='categoria_dre',
            field=models.ForeignKey(blank=True, help_text='Categoria para o relatório DRE', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_pagar', to='financeiro.categoriadre', verbose_name='Categoria DRE'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='categoria_dre',
            field=models.ForeignKey(blank=True, help_text='Categoria para o relatório DRE', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_receber', to='financeiro.categoriadre', verbose_name='Categoria DRE'),
        ),
    ]
