# Generated by Django 4.2.8 on 2025-11-26 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistencia', '0002_checklistitem_servicotemplate_termogarantia_and_more'),
        ('financeiro', '0003_contapagar_categoria_dre_contareceber_categoria_dre'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('pix', 'PIX'), ('boleto', 'Boleto'), ('transferencia', 'Transferência')], max_length=20)),
                ('taxa_percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('taxa_fixa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('permite_parcelamento', models.BooleanField(default=False)),
                ('max_parcelas', models.IntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxa_maquina', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_liquido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_parcelas', models.IntegerField(default=1)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.formapagamento')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='assistencia.ordemservico')),
            ],
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('recebido', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True)),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='financeiro.pagamento')),
            ],
            options={
                'ordering': ['numero_parcela'],
            },
        ),
    ]
