# Generated by Django 4.2.8 on 2025-11-26 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_formapagamento_pagamento_parcela'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaRecebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Débito Visa, Crédito Master, PIX', max_length=100, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('pix', 'PIX'), ('boleto', 'Boleto'), ('transferencia', 'Transferência Bancária'), ('cheque', 'Cheque')], max_length=20, verbose_name='Tipo')),
                ('taxa_percentual', models.DecimalField(decimal_places=2, default=0, help_text='Taxa percentual cobrada pela operadora (ex: 2.5 para 2,5%)', max_digits=5, verbose_name='Taxa Percentual (%)')),
                ('taxa_fixa', models.DecimalField(decimal_places=2, default=0, help_text='Taxa fixa por transação', max_digits=10, verbose_name='Taxa Fixa (R$)')),
                ('permite_parcelamento', models.BooleanField(default=False, verbose_name='Permite Parcelamento')),
                ('max_parcelas', models.IntegerField(default=1, verbose_name='Máximo de Parcelas')),
                ('taxa_parcelado_2x', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Taxa 2x (%)')),
                ('taxa_parcelado_3x', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Taxa 3x (%)')),
                ('taxa_parcelado_4_6x', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Taxa 4-6x (%)')),
                ('taxa_parcelado_7_12x', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Taxa 7-12x (%)')),
                ('dias_recebimento', models.IntegerField(default=0, help_text='Quantos dias até o dinheiro cair na conta (ex: 30 dias)', verbose_name='Dias para Recebimento')),
                ('operadora', models.CharField(blank=True, help_text='Ex: Cielo, Stone, PagSeguro', max_length=100, verbose_name='Operadora/Bandeira')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Forma de Recebimento',
                'verbose_name_plural': 'Formas de Recebimento',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='forma_pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.formarecebimento'),
        ),
        migrations.DeleteModel(
            name='FormaPagamento',
        ),
    ]
