# Generated by Django 4.2.26 on 2025-11-23 02:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Início')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('status', models.CharField(choices=[('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='em_andamento', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Inventário',
                'verbose_name_plural': 'Inventários',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('ajuste', 'Ajuste'), ('transferencia', 'Transferência'), ('inventario', 'Inventário')], max_length=20, verbose_name='Tipo')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade')),
                ('quantidade_anterior', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Quantidade Anterior')),
                ('quantidade_nova', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Quantidade Nova')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total')),
                ('motivo', models.CharField(blank=True, max_length=200, verbose_name='Motivo')),
                ('documento', models.CharField(blank=True, choices=[('nota_fiscal', 'Nota Fiscal'), ('pedido', 'Pedido'), ('os', 'Ordem de Serviço'), ('venda', 'Venda'), ('ajuste_manual', 'Ajuste Manual'), ('inventario', 'Inventário'), ('transferencia', 'Transferência')], max_length=20, verbose_name='Tipo de Documento')),
                ('documento_numero', models.CharField(blank=True, max_length=50, verbose_name='Número do Documento')),
                ('lote', models.CharField(blank=True, max_length=50, verbose_name='Lote')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
                ('local_origem', models.CharField(blank=True, max_length=100, verbose_name='Local de Origem')),
                ('local_destino', models.CharField(blank=True, max_length=100, verbose_name='Local de Destino')),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Movimentação')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='erp.produto', verbose_name='Produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_estoque', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data_movimentacao'],
                'indexes': [models.Index(fields=['produto', '-data_movimentacao'], name='estoque_mov_produto_345496_idx'), models.Index(fields=['tipo', '-data_movimentacao'], name='estoque_mov_tipo_6019ee_idx'), models.Index(fields=['-data_movimentacao'], name='estoque_mov_data_mo_3d05e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('numero_lote', models.CharField(max_length=50, verbose_name='Número do Lote')),
                ('data_fabricacao', models.DateField(blank=True, null=True, verbose_name='Data de Fabricação')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
                ('quantidade', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade')),
                ('nota_fiscal', models.CharField(blank=True, max_length=50, verbose_name='Nota Fiscal')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='erp.fornecedor', verbose_name='Fornecedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='erp.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['data_validade', 'numero_lote'],
                'indexes': [models.Index(fields=['produto', 'data_validade'], name='estoque_lot_produto_74178e_idx'), models.Index(fields=['numero_lote'], name='estoque_lot_numero__64ce7f_idx')],
                'unique_together': {('produto', 'numero_lote')},
            },
        ),
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_sistema', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Quantidade no Sistema')),
                ('quantidade_contada', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Quantidade Contada')),
                ('diferenca', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Diferença')),
                ('valor_diferenca', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor da Diferença')),
                ('ajustado', models.BooleanField(default=False, verbose_name='Ajustado')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.inventario', verbose_name='Inventário')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_inventario', to='erp.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item de Inventário',
                'verbose_name_plural': 'Itens de Inventário',
                'ordering': ['produto__nome'],
                'unique_together': {('inventario', 'produto')},
            },
        ),
    ]
