# Generated by Django 4.2.26 on 2025-11-23 02:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Solicitação')),
                ('data_validade', models.DateField(verbose_name='Data de Validade')),
                ('status', models.CharField(choices=[('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='em_andamento', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotacoes', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Cotação',
                'verbose_name_plural': 'Cotações',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_pedida', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Quantidade Pedida')),
                ('quantidade_recebida', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Quantidade Recebida')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço Unitário')),
                ('preco_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço Total')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto')),
            ],
            options={
                'verbose_name': 'Item do Pedido de Compra',
                'verbose_name_plural': 'Itens do Pedido de Compra',
                'ordering': ['produto__nome'],
            },
        ),
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número')),
                ('data_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pedido')),
                ('data_entrega_prevista', models.DateField(verbose_name='Data de Entrega Prevista')),
                ('data_entrega_real', models.DateField(blank=True, null=True, verbose_name='Data de Entrega Real')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('em_transito', 'Em Trânsito'), ('recebido', 'Recebido'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('valor_produtos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor dos Produtos')),
                ('valor_frete', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do Frete')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do Desconto')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total')),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('boleto', 'Boleto'), ('transferencia', 'Transferência'), ('cartao', 'Cartão'), ('cheque', 'Cheque')], default='boleto', max_length=20, verbose_name='Forma de Pagamento')),
                ('condicao_pagamento', models.CharField(blank=True, max_length=100, verbose_name='Condição de Pagamento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_compra', to=settings.AUTH_USER_MODEL, verbose_name='Comprador')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_compra', to='erp.fornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Pedido de Compra',
                'verbose_name_plural': 'Pedidos de Compra',
                'ordering': ['-data_pedido'],
            },
        ),
        migrations.CreateModel(
            name='RecebimentoMercadoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nota_fiscal', models.CharField(max_length=50, verbose_name='Nota Fiscal')),
                ('data_recebimento', models.DateTimeField(auto_now_add=True, verbose_name='Data de Recebimento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('pedido_compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos', to='compras.pedidocompra', verbose_name='Pedido de Compra')),
                ('recebedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos', to=settings.AUTH_USER_MODEL, verbose_name='Recebedor')),
            ],
            options={
                'verbose_name': 'Recebimento de Mercadoria',
                'verbose_name_plural': 'Recebimentos de Mercadorias',
                'ordering': ['-data_recebimento'],
            },
        ),
        migrations.CreateModel(
            name='ItemRecebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Quantidade')),
                ('lote', models.CharField(blank=True, max_length=50, verbose_name='Lote')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
                ('conferido', models.BooleanField(default=False, verbose_name='Conferido')),
                ('item_pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos', to='compras.itempedidocompra', verbose_name='Item do Pedido')),
                ('recebimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.recebimentomercadoria', verbose_name='Recebimento')),
            ],
            options={
                'verbose_name': 'Item do Recebimento',
                'verbose_name_plural': 'Itens do Recebimento',
            },
        ),
        migrations.AddField(
            model_name='itempedidocompra',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.pedidocompra', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='itempedidocompra',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido_compra', to='erp.produto', verbose_name='Produto'),
        ),
        migrations.CreateModel(
            name='ItemCotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço Unitário')),
                ('preco_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço Total')),
                ('prazo_entrega', models.IntegerField(default=0, verbose_name='Prazo de Entrega (dias)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('cotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.cotacao', verbose_name='Cotação')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_cotacao', to='erp.fornecedor', verbose_name='Fornecedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_cotacao', to='erp.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item de Cotação',
                'verbose_name_plural': 'Itens de Cotação',
                'ordering': ['produto__nome', 'preco_unitario'],
            },
        ),
        migrations.AddIndex(
            model_name='pedidocompra',
            index=models.Index(fields=['numero'], name='compras_ped_numero_799849_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidocompra',
            index=models.Index(fields=['fornecedor', '-data_pedido'], name='compras_ped_fornece_48a297_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidocompra',
            index=models.Index(fields=['status'], name='compras_ped_status_6040b7_idx'),
        ),
    ]
