# Generated by Django 4.2.26 on 2025-11-23 03:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaFunil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('cor', models.CharField(default='#10B981', max_length=7, verbose_name='Cor (Hex)')),
                ('probabilidade', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Probabilidade de Fechamento (%)')),
                ('is_inicial', models.BooleanField(default=False, verbose_name='Etapa Inicial')),
                ('is_ganho', models.BooleanField(default=False, verbose_name='Etapa de Ganho')),
                ('is_perdido', models.BooleanField(default=False, verbose_name='Etapa de Perda')),
            ],
            options={
                'verbose_name': 'Etapa do Funil',
                'verbose_name_plural': 'Etapas do Funil',
                'ordering': ['funil', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='Funil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('cor', models.CharField(default='#3B82F6', max_length=7, verbose_name='Cor (Hex)')),
            ],
            options={
                'verbose_name': 'Funil de Vendas',
                'verbose_name_plural': 'Funis de Vendas',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('nome_lead', models.CharField(blank=True, max_length=200, verbose_name='Nome do Lead')),
                ('email_lead', models.EmailField(blank=True, max_length=254, verbose_name='E-mail do Lead')),
                ('telefone_lead', models.CharField(blank=True, max_length=20, verbose_name='Telefone do Lead')),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Estimado')),
                ('probabilidade', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Probabilidade (%)')),
                ('data_abertura', models.DateField(auto_now_add=True, verbose_name='Data de Abertura')),
                ('data_fechamento_prevista', models.DateField(blank=True, null=True, verbose_name='Data Prevista de Fechamento')),
                ('data_fechamento', models.DateField(blank=True, null=True, verbose_name='Data de Fechamento')),
                ('origem', models.CharField(choices=[('website', 'Website'), ('indicacao', 'Indicação'), ('telefone', 'Telefone'), ('email', 'E-mail'), ('redes_sociais', 'Redes Sociais'), ('evento', 'Evento'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='Origem')),
                ('motivo_perda', models.TextField(blank=True, verbose_name='Motivo da Perda')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades', to='erp.cliente', verbose_name='Cliente')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades', to='crm.etapafunil', verbose_name='Etapa Atual')),
                ('funil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades', to='crm.funil', verbose_name='Funil')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to='erp.produto', verbose_name='Produto/Serviço')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Oportunidade',
                'verbose_name_plural': 'Oportunidades',
                'ordering': ['-data_abertura'],
            },
        ),
        migrations.CreateModel(
            name='Interacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo', models.CharField(choices=[('ligacao', 'Ligação'), ('email', 'E-mail'), ('reuniao', 'Reunião'), ('visita', 'Visita'), ('whatsapp', 'WhatsApp'), ('nota', 'Nota'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('assunto', models.CharField(max_length=200, verbose_name='Assunto')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_interacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Interação')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='erp.cliente', verbose_name='Cliente')),
                ('oportunidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='crm.oportunidade', verbose_name='Oportunidade')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interacoes_crm', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Interação',
                'verbose_name_plural': 'Interações',
                'ordering': ['-data_interacao'],
            },
        ),
        migrations.AddField(
            model_name='etapafunil',
            name='funil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='crm.funil', verbose_name='Funil'),
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo', models.CharField(choices=[('ligacao', 'Ligação'), ('email', 'E-mail'), ('reuniao', 'Reunião'), ('visita', 'Visita'), ('proposta', 'Enviar Proposta'), ('follow_up', 'Follow-up'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data_prevista', models.DateTimeField(verbose_name='Data Prevista')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status')),
                ('resultado', models.TextField(blank=True, verbose_name='Resultado')),
                ('oportunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='crm.oportunidade', verbose_name='Oportunidade')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades_crm', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'ordering': ['data_prevista'],
            },
        ),
        migrations.AddIndex(
            model_name='oportunidade',
            index=models.Index(fields=['numero'], name='crm_oportun_numero_4377c3_idx'),
        ),
        migrations.AddIndex(
            model_name='oportunidade',
            index=models.Index(fields=['cliente', '-data_abertura'], name='crm_oportun_cliente_7b418f_idx'),
        ),
        migrations.AddIndex(
            model_name='oportunidade',
            index=models.Index(fields=['etapa'], name='crm_oportun_etapa_i_3f0b3b_idx'),
        ),
        migrations.AddIndex(
            model_name='oportunidade',
            index=models.Index(fields=['responsavel', '-data_abertura'], name='crm_oportun_respons_b2d944_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='etapafunil',
            unique_together={('funil', 'ordem')},
        ),
    ]
