# Generated by Django 4.2.8 on 2025-11-28 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora de Abertura')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Fechamento')),
                ('valor_inicial', models.DecimalField(decimal_places=2, help_text='Valor em dinheiro contado na abertura do caixa', max_digits=10, verbose_name='Valor Inicial (Contagem Física)')),
                ('valor_final', models.DecimalField(blank=True, decimal_places=2, help_text='Valor em dinheiro contado no fechamento do caixa', max_digits=10, null=True, verbose_name='Valor Final (Contagem Física)')),
                ('valor_esperado', models.DecimalField(blank=True, decimal_places=2, help_text='Valor calculado baseado nas vendas', max_digits=10, null=True, verbose_name='Valor Esperado')),
                ('observacoes_abertura', models.TextField(blank=True, verbose_name='Observações da Abertura')),
                ('observacoes_fechamento', models.TextField(blank=True, verbose_name='Observações do Fechamento')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado')], default='aberto', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario_abertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caixas_abertos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que abriu')),
                ('usuario_fechamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='caixas_fechados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que fechou')),
            ],
            options={
                'verbose_name': 'Caixa',
                'verbose_name_plural': 'Caixas',
                'ordering': ['-data_abertura'],
                'indexes': [models.Index(fields=['status', 'usuario_abertura'], name='caixa_caixa_status_93b260_idx'), models.Index(fields=['data_abertura'], name='caixa_caixa_data_ab_31a1b4_idx')],
            },
        ),
    ]
