# Generated by Django 4.2.26 on 2025-11-23 02:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número')),
                ('equipamento', models.CharField(max_length=200, verbose_name='Equipamento')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='Número de Série')),
                ('acessorios', models.TextField(blank=True, help_text='Ex: Carregador, capa, etc.', verbose_name='Acessórios')),
                ('defeito_relatado', models.TextField(verbose_name='Defeito Relatado')),
                ('observacoes_cliente', models.TextField(blank=True, verbose_name='Observações do Cliente')),
                ('diagnostico', models.TextField(blank=True, verbose_name='Diagnóstico Técnico')),
                ('solucao', models.TextField(blank=True, verbose_name='Solução')),
                ('data_abertura', models.DateTimeField(auto_now_add=True, verbose_name='Data de Abertura')),
                ('data_previsao', models.DateField(blank=True, null=True, verbose_name='Previsão de Entrega')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('data_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Data de Entrega')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_diagnostico', 'Em Diagnóstico'), ('orcamento', 'Aguardando Orçamento'), ('aprovada', 'Aprovada'), ('em_execucao', 'Em Execução'), ('aguardando_peca', 'Aguardando Peça'), ('concluida', 'Concluída'), ('entregue', 'Entregue'), ('cancelada', 'Cancelada')], default='aberta', max_length=20, verbose_name='Status')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10, verbose_name='Prioridade')),
                ('valor_servico', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do Serviço')),
                ('valor_pecas', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor das Peças')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do Desconto')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total')),
                ('garantia_dias', models.IntegerField(default=90, verbose_name='Garantia (dias)')),
                ('data_fim_garantia', models.DateField(blank=True, null=True, verbose_name='Fim da Garantia')),
                ('observacoes_internas', models.TextField(blank=True, verbose_name='Observações Internas')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='erp.cliente', verbose_name='Cliente')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsável')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-data_abertura'],
            },
        ),
        migrations.CreateModel(
            name='PecaOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço Unitário')),
                ('preco_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço Total')),
                ('aplicada', models.BooleanField(default=False, verbose_name='Aplicada')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas', to='assistencia.ordemservico', verbose_name='Ordem de Serviço')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pecas_os', to='erp.produto', verbose_name='Produto/Peça')),
            ],
            options={
                'verbose_name': 'Peça da OS',
                'verbose_name_plural': 'Peças da OS',
                'ordering': ['produto__nome'],
            },
        ),
        migrations.CreateModel(
            name='OrcamentoOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('descricao_servico', models.TextField(verbose_name='Descrição do Serviço')),
                ('valor_servico', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor do Serviço')),
                ('valor_pecas', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor das Peças')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total')),
                ('prazo_dias', models.IntegerField(default=7, verbose_name='Prazo (dias)')),
                ('validade_dias', models.IntegerField(default=15, verbose_name='Validade do Orçamento (dias)')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='assistencia.ordemservico', verbose_name='Ordem de Serviço')),
            ],
            options={
                'verbose_name': 'Orçamento da OS',
                'verbose_name_plural': 'Orçamentos da OS',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('acao', models.CharField(max_length=100, verbose_name='Ação')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='assistencia.ordemservico', verbose_name='Ordem de Serviço')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_os', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico da OS',
                'verbose_name_plural': 'Históricos da OS',
                'ordering': ['-data'],
            },
        ),
        migrations.AddIndex(
            model_name='ordemservico',
            index=models.Index(fields=['numero'], name='assistencia_numero_538ef4_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemservico',
            index=models.Index(fields=['cliente', '-data_abertura'], name='assistencia_cliente_057dc4_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemservico',
            index=models.Index(fields=['status'], name='assistencia_status_70511a_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemservico',
            index=models.Index(fields=['tecnico', '-data_abertura'], name='assistencia_tecnico_56e343_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemservico',
            index=models.Index(fields=['-data_abertura'], name='assistencia_data_ab_93b708_idx'),
        ),
    ]
