# Generated by Django 4.2.8 on 2025-11-26 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ordem', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ServicoTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(max_length=200)),
                ('descricao_detalhada', models.TextField(blank=True)),
                ('valor_padrao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tempo_estimado', models.IntegerField(blank=True, help_text='Tempo em minutos', null=True)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='TermoGarantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('produto', 'Produto'), ('servico', 'Serviço')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('padrao', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Termo de Garantia',
                'verbose_name_plural': 'Termos de Garantia',
            },
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='checklist',
            field=models.JSONField(blank=True, default=dict, verbose_name='Checklist'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=50, verbose_name='Forma de Pagamento'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='laudo_tecnico',
            field=models.TextField(blank=True, verbose_name='Laudo Técnico'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='obs_recebimento',
            field=models.TextField(blank=True, verbose_name='Obs. Recebimento'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='protocolo_entrega',
            field=models.BooleanField(default=False, verbose_name='Protocolo de Entrega'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='valor_frete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do Frete'),
        ),
        migrations.CreateModel(
            name='OSAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='os_anexos/')),
                ('tipo', models.CharField(max_length=50)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='assistencia.ordemservico')),
            ],
            options={
                'verbose_name': 'Anexo da OS',
                'verbose_name_plural': 'Anexos da OS',
            },
        ),
    ]
