# Generated by Django 4.2.8 on 2025-11-26 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistencia', '0003_categoriaservico_alter_servicotemplate_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicotemplate',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicos', to='assistencia.categoriaservico', verbose_name='Categoria'),
        ),
    ]
